### ISSUE TITLE
dev fails: webpack: `optionsSchema.definitions.output` undefined

### ISSUE THREAD

**Issue by vogler** [Kiho/svelte-roadtrip-todo#1]
Was just looking for a Svelte+Typescript example and tried to run `npm install && npm run dev` but it failed:
~~~
> svelte-roadtrip-todo@0.5.0 dev /Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo
> concurrently "npm run watch"  "npm run dev1"

[0]
[0] > svelte-roadtrip-todo@0.5.0 watch /Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo
[0] > webpack -w
[0]
[1]
[1] > svelte-roadtrip-todo@0.5.0 dev1 /Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo
[1] > cross-env NODE_ENV=development && npm run serve:dev
[1]
[0] /Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo/node_modules/webpack-cli/bin/config-yargs.js:89
[0] 				describe: optionsSchema.definitions.output.properties.path.description,
[0] 				                                           ^
[0]
[0] TypeError: Cannot read property 'properties' of undefined
[0]     at module.exports (/Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo/node_modules/webpack-cli/bin/config-yargs.js:89:48)
[0]     at /Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo/node_modules/webpack-cli/bin/webpack.js:60:27
[0]     at Object.<anonymous> (/Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo/node_modules/webpack-cli/bin/webpack.js:515:3)
[0]     at Module._compile (internal/modules/cjs/loader.js:956:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
[0]     at Module.load (internal/modules/cjs/loader.js:812:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
[0]     at Module.require (internal/modules/cjs/loader.js:849:19)
[0]     at require (internal/modules/cjs/helpers.js:74:18)
[0]     at Object.<anonymous> (/Users/voglerr/dev/templates/svelte/svelte-roadtrip-todo/node_modules/webpack/bin/webpack.js:156:2)
~~~

**Comment by Kiho** [comment]
You can run the code with old version of webpack.
However, this only works with svelte v2 which is outdated.

**Comment by vogler** [comment]
Thanks, works now.
